### ISSUE TITLE
trying to embed the generated  js into html

### ISSUE THREAD

**Issue by levnach** [msaglJS/msagl-js#6]
@assafsun 
I created createSvg.html file. Cannot past it in the comment but here is the link https://github.com/msaglJS/msagl-js/blob/master/src/tests/createSvg.html. 
I am getting an error when clicking on the button in Chrome: 
layeredLayout.spec.js:2 Uncaught ReferenceError: exports is not defined
    at layeredLayout.spec.js:2
The line in question is 
Object.defineProperty(exports, "__esModule", { value: true });
How is it supposed to work?
Reading about this online but still no light.

**Comment by assafsun** [comment]
@levnach talked about it. closing this issue for now.
